project_id = "tqxhcyuxgqbzqwoidpie"
[functions.yampi-lookup-sku]
verify_jwt = false


[functions.yampi-create-payment-link]
verify_jwt = false

[functions.yampi-webhook]
verify_jwt = false

[functions.shopify-get-variant-sku]
verify_jwt = false

[functions.meta-whatsapp-webhook]
verify_jwt = false

[functions.meta-whatsapp-send]
verify_jwt = false

[functions.meta-whatsapp-send-template]
verify_jwt = false

[functions.meta-whatsapp-get-templates]
verify_jwt = false

[functions.meta-whatsapp-create-template]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.paypal-get-order]
verify_jwt = false

[functions.shopify-create-draft-order]
verify_jwt = false

[functions.mercadopago-create-pix]
verify_jwt = false