ALTER TABLE public.automation_message_queue
  ADD COLUMN IF NOT EXISTS queue_seq bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_automation_queue_phone_flow_seq
  ON public.automation_message_queue (phone, flow_id, queue_seq)
  WHERE status IN ('pending','sending');

CREATE OR REPLACE FUNCTION public.claim_automation_queue_jobs(p_worker_id text, p_batch_size integer DEFAULT 30, p_lease_seconds integer DEFAULT 120, p_max_attempts integer DEFAULT 3)
 RETURNS SETOF automation_message_queue
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  RETURN QUERY
  WITH due AS (
    SELECT q.id
    FROM public.automation_message_queue q
    WHERE q.scheduled_at <= now()
      AND q.attempts < p_max_attempts
      AND (
        q.status = 'pending'
        OR (q.status = 'sending' AND (q.locked_until IS NULL OR q.locked_until < now()))
      )
      -- Preserva a ordem dos blocos: só sai o bloco mais antigo ainda pendente
      -- do mesmo contato no mesmo fluxo (reagendamentos com jitter não invertem a ordem).
      AND NOT EXISTS (
        SELECT 1 FROM public.automation_message_queue e
        WHERE e.phone = q.phone
          AND e.flow_id IS NOT DISTINCT FROM q.flow_id
          AND e.queue_seq < q.queue_seq
          AND e.status IN ('pending','sending')
          AND e.attempts < p_max_attempts
      )
    ORDER BY q.scheduled_at
    LIMIT p_batch_size
    FOR UPDATE SKIP LOCKED
  )
  UPDATE public.automation_message_queue q
  SET status = 'sending',
      locked_by = p_worker_id,
      locked_until = now() + make_interval(secs => p_lease_seconds),
      attempts = q.attempts + 1,
      updated_at = now()
  FROM due
  WHERE q.id = due.id
  RETURNING q.*;
END;
$function$;