CREATE OR REPLACE VIEW public.crm_customers_v AS
 SELECT id,
    customer_code AS zoppy_id,
    NULLIF(split_part(COALESCE(name, ''::text), ' '::text, 1), ''::text) AS first_name,
    NULLIF(btrim(SUBSTRING(COALESCE(name, ''::text) FROM POSITION((' '::text) IN (COALESCE(name, ''::text))) + 1)), ''::text) AS last_name,
    name,
    phone_e164 AS phone,
    phone_e164,
    phone_suffix8,
    email,
    cpf,
    city,
    state,
    COALESCE(NULLIF(btrim(region_type), ''::text), 'online'::text) AS region_type,
    ddd,
    rfm_r AS rfm_recency_score,
    rfm_f AS rfm_frequency_score,
    rfm_m AS rfm_monetary_score,
    rfm_total AS rfm_total_score,
    rfm_segment,
    total_orders,
    total_spent,
    avg_ticket,
    last_purchase_at,
    first_purchase_at,
    tags,
    opt_out_mass_dispatch,
    is_archived,
    created_at,
    updated_at,
    gender,
    purchased_brands,
    purchased_categories,
    purchased_sizes,
    purchased_stores,
    payment_methods
   FROM customers_unified cu
  WHERE is_archived = false;